variables:
  - group: aws-group
  - group: common
  - group: nomad-variables
  
trigger: none
  
stages:

- stage: Deploy_Nomad_Job
  displayName: Setup Step
  jobs:
  - job:
    pool: $(agent_pool)
    steps:
    - template: templates/add-whitelist-aws-template.yml
    - template: templates/deploy-nomad-job.yml
